### PR TITLE
Added new Smashrun APIs: polyline, notables, splits

### PR DESCRIPTION
**Pull request by nall**
Updated docs for search to include extended

### CODE REVIEW

**Comment by campbellr** [comment]
Looks great, thanks. 

I'll take a closer look and merge this in tonight.

**Comment by campbellr** [comment]
@nall Looks good to me, but do you mind rebasing your changes off the latest commits in `master`? I added some travis-ci stuff to run tests and the flake8 tool against PRs that I would like to try out.

Thanks!

**Comment by nall** [comment]
@campbellr OK, I think it should be good to go now. Thanks!

**Comment by campbellr** [comment]
Awesome. Thanks for being a guinea pig :grin:

**Comment by nall** [comment]
Very cool setup!

**Pull request merged**
