### PR TITLE
Added APIs for new activity PUT/DELETE methods

### PR DESCRIPTION
**Pull request by nall**
The Smashrun team updated their API this weekend to add put and delete methods. Here's a patch to add API to this library to enable them.

Reference thread: http://discuss.smashrun.com/t/updating-runs-via-api/103/7

nall.

### CODE REVIEW

**Comment by campbellr** [comment]
Looks great, thanks @nall

**Comment by nall** [comment]
@campbellr Could you push out a new version with update support?

**Comment by campbellr** [comment]
@nall Sorry I had meant to make a new release earlier but completely forgot.

I'll make one tonight.

**Comment by campbellr** [comment]
@nall There you go. I just published 0.5.0 on PyPI.

**Comment by nall** [comment]
thanks!

**Pull request merged**
